package nonprofitbookkeeping.reports.jasper.model;

// TODO: Auto-generated Javadoc
/**
 * Describes a dynamic data field discovered in an Excel sheet.
 * Generated by the SheetModelBuilder and consumed by JRXML/bean/fieldmap generators.
 */
public final class FieldInfo
{
    
    /** The field name. */
    private final String fieldName;
    
    /** The java type. */
    private final String javaType;
    
    /** The excel format. */
    private final String excelFormat;

    /**
     * Instantiates a new field info.
     *
     * @param fieldName the field name
     * @param javaType the java type
     * @param excelFormat the excel format
     */
    public FieldInfo(String fieldName, String javaType, String excelFormat)
    {
        this.fieldName = fieldName;
        this.javaType = javaType;
        this.excelFormat = excelFormat;
    }

    /**
     * Instantiates a new field info.
     *
     * @param fieldName the field name
     * @param javaType the java type
     */
    public FieldInfo(String fieldName, String javaType)
    {
        this(fieldName, javaType, null);
    }

    /**
     * Field name.
     *
     * @return the string
     */
    public String fieldName()
    {
        return this.fieldName;
    }

    /**
     * Java type.
     *
     * @return the string
     */
    public String javaType()
    {
        return this.javaType;
    }

    /**
     * Excel format.
     *
     * @return the string
     */
    public String excelFormat()
    {
        return this.excelFormat;
    }
}