package nonprofitbookkeeping.reports.jasper.model;

/**
 * Describes a dynamic data field discovered in an Excel sheet.
 * Generated by the SheetModelBuilder and consumed by JRXML/bean/fieldmap generators.
 */
public final class FieldInfo
{
    private final String fieldName;
    private final String javaType;
    private final String excelFormat;

    public FieldInfo(String fieldName, String javaType, String excelFormat)
    {
        this.fieldName = fieldName;
        this.javaType = javaType;
        this.excelFormat = excelFormat;
    }

    public FieldInfo(String fieldName, String javaType)
    {
        this(fieldName, javaType, null);
    }

    public String fieldName()
    {
        return this.fieldName;
    }

    public String javaType()
    {
        return this.javaType;
    }

    public String excelFormat()
    {
        return this.excelFormat;
    }
}