package nonprofitbookkeeping.model.budget;

import lombok.Data;
import lombok.NoArgsConstructor; // For Jackson
// No @AllArgsConstructor to allow custom constructor logic for budgetId

import java.util.List;
import java.util.ArrayList;
import java.util.UUID;

@Data
@NoArgsConstructor // Keep for Jackson, but ensure budgetId is handled if object created this way
public class Budget {
    private String budgetId;
    private String budgetName;
    private int fiscalYear;
    private String description; // Optional
    private List<BudgetLine> budgetLines = new ArrayList<>();
    private String currency; // Should match company currency
    private String applicableFundId; // Optional

    /**
     * Constructor with essential fields.
     * Generates a budgetId if not already set (e.g. during deserialization).
     * @param budgetName The name of the budget.
     * @param fiscalYear The fiscal year of the budget.
     */
    public Budget(String budgetName, int fiscalYear) {
        this.budgetId = UUID.randomUUID().toString(); // Generate new ID
        this.budgetName = budgetName;
        this.fiscalYear = fiscalYear;
        // budgetLines is initialized
    }
    
    // Custom getter for budgetId to ensure it's initialized if null
    // This is useful if the object was created with @NoArgsConstructor (e.g., by Jackson)
    // and not subsequently populated with an ID.
    public String getBudgetId() {
        if (this.budgetId == null) {
            this.budgetId = UUID.randomUUID().toString();
        }
        return this.budgetId;
    }
    
    // Ensure budgetId is set upon construction if using @NoArgsConstructor path,
    // though this is better handled by having Jackson populate it or using a factory.
    // For robust handling with @NoArgsConstructor, budgetId might need to be checked/set
    // upon first access or through a specific init method if not deserialized.
    // The getter approach above is a common pattern.

    public void addBudgetLine(BudgetLine line) {
        if (this.budgetLines == null) {
            this.budgetLines = new ArrayList<>();
        }
        this.budgetLines.add(line);
    }

    public void removeBudgetLine(BudgetLine line) {
        if (this.budgetLines != null) {
            this.budgetLines.remove(line);
        }
    }

    // Standard setters and getters will be generated by @Data
    // No need to explicitly write them unless custom logic is needed.
}
