# Generated metadata for Jasper report bundle
displayName=Newsletter 15
generatorClass=nonprofitbookkeeping.reports.jasper.Newsletter15JasperGenerator
reportType=SCA_NEWSLETTER_15_JASPER
template=NEWSLETTER_15.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.Newsletter15Bean
beanName=Newsletter15Bean
description=Newsletter schedule 15. Data bean: Newsletter15Bean.
