# Generated metadata for Jasper report bundle
displayName=Asset Detail 5a
generatorClass=nonprofitbookkeeping.reports.jasper.AssetDtl5aJasperGenerator
reportType=SCA_ASSET_DTL_5A_JASPER
template=ASSET_DTL_5a.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.AssetDtl5aBean
beanName=AssetDtl5aBean
description=SCA schedule Asset Detail 5a. Data bean: AssetDtl5aBean.
