# Generated metadata for Jasper report bundle
displayName=General Journal
generatorClass=nonprofitbookkeeping.reports.jasper.GeneralJournalJasperGenerator
reportType=GENERAL_JOURNAL_JASPER
template=GeneralJournal.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.GeneralJournalRowBean
description=Journal transaction listing. Data bean: GeneralJournalRowBean.
beanName=generalJournalRow
