# Generated metadata for Jasper report bundle
displayName=Primary Account Reconciliation
generatorClass=nonprofitbookkeeping.reports.jasper.PrimaryAccountReconciliationJasperGenerator
reportType=SCA_PRIMARY_ACCOUNT_RECONCILIATION_JASPER
template=PRIMARY_ACCOUNT_2a.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.PrimaryAccount2aBean
beanName=PrimaryAccount2aBean
description=Primary account reconciliation leveraging PrimaryAccount2aBean.
