# Generated metadata for Jasper report bundle
displayName=Primary Account 2a
generatorClass=nonprofitbookkeeping.reports.jasper.PrimaryAccountJasperGenerator
reportType=SCA_PRIMARY_ACCOUNT_JASPER
template=PRIMARY_ACCOUNT_2a.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.PrimaryAccount2aBean
description=Primary account schedule 2a. Data bean: PrimaryAccount2aBean.
beanName=primaryAccount2a
