BEGIN;

-- Strict transfer lifecycle vocabulary.
ALTER TABLE fund_transfer
  ADD CONSTRAINT IF NOT EXISTS chk_fund_transfer_status_domain
  CHECK (status IN ('DRAFT','APPROVED','POSTING','POSTED','FAILED','VOIDED'));

-- Posting link must agree with lifecycle state.
ALTER TABLE fund_transfer
  ADD CONSTRAINT IF NOT EXISTS chk_fund_transfer_posted_link_by_status
  CHECK (
    (status = 'POSTED' AND posted_txn_id IS NOT NULL)
    OR
    (status <> 'POSTED' AND posted_txn_id IS NULL)
  );

-- One canonical posting txn can represent at most one transfer.
ALTER TABLE fund_transfer
  ADD CONSTRAINT IF NOT EXISTS uq_fund_transfer_posted_txn UNIQUE (posted_txn_id);

-- Operational indexes for posting queues and review workflows.
CREATE INDEX IF NOT EXISTS ix_fund_transfer_status_date
  ON fund_transfer(status, transfer_date, id);

CREATE INDEX IF NOT EXISTS ix_fund_transfer_from_to_date
  ON fund_transfer(from_fund_id, to_fund_id, transfer_date, id);

-- Status transition matrix (trigger/service guard source of truth).
CREATE TABLE IF NOT EXISTS fund_transfer_status_transition (
  from_status VARCHAR(20) NOT NULL,
  to_status   VARCHAR(20) NOT NULL,
  is_allowed  BOOLEAN NOT NULL,
  notes       VARCHAR(300),
  CONSTRAINT pk_fund_transfer_status_transition PRIMARY KEY (from_status, to_status)
);

MERGE INTO fund_transfer_status_transition (from_status, to_status, is_allowed, notes)
KEY (from_status, to_status)
VALUES
  ('DRAFT', 'APPROVED', TRUE, 'Ready for posting.'),
  ('DRAFT', 'VOIDED', TRUE, 'Cancelled before approval.'),
  ('APPROVED', 'POSTING', TRUE, 'Posting transaction started.'),
  ('APPROVED', 'VOIDED', TRUE, 'Cancelled after approval.'),
  ('POSTING', 'POSTED', TRUE, 'Atomic post complete.'),
  ('POSTING', 'FAILED', TRUE, 'Posting failed; no posting txn persisted.'),
  ('FAILED', 'APPROVED', TRUE, 'Retry after remediation.'),
  ('FAILED', 'VOIDED', TRUE, 'Abandon failed transfer.'),
  ('POSTED', 'VOIDED', FALSE, 'Disallow direct void; require reversing transfer.'),
  ('VOIDED', 'DRAFT', FALSE, 'No reopen from void.');

-- Recommended trigger target table: write one row per transition/check failure.
-- Engines with SQL trigger support can enforce in DB directly.
CREATE TABLE IF NOT EXISTS fund_transfer_integrity_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id BIGINT NOT NULL,
  event_type VARCHAR(40) NOT NULL,
  event_detail VARCHAR(1000),
  detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT fk_ft_integrity_event_transfer
    FOREIGN KEY (transfer_id) REFERENCES fund_transfer(id) ON DELETE CASCADE
);

-- Repair queue used by validation + manual remediation workflow.
CREATE TABLE IF NOT EXISTS fund_transfer_repair_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transfer_id BIGINT NOT NULL,
  issue_code VARCHAR(60) NOT NULL,
  issue_detail VARCHAR(1000),
  proposed_action VARCHAR(500),
  detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  resolved_at TIMESTAMP,
  resolved_by VARCHAR(120),
  resolution_note VARCHAR(1000),
  CONSTRAINT fk_ft_repair_transfer
    FOREIGN KEY (transfer_id) REFERENCES fund_transfer(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_ft_repair_open
  ON fund_transfer_repair_queue(resolved_at, issue_code, detected_at);

COMMIT;
