-- Prompt G: Grant/Donor/Program Traceability
-- Forward migration (H2-compatible)

-- 1) Extend grant_record for compliance, program, and posting traceability.
ALTER TABLE grant_record
  ADD COLUMN IF NOT EXISTS award_date DATE,
  ADD COLUMN IF NOT EXISTS period_start DATE,
  ADD COLUMN IF NOT EXISTS period_end DATE,
  ADD COLUMN IF NOT EXISTS restriction_class VARCHAR(32) DEFAULT 'RESTRICTED' NOT NULL,
  ADD COLUMN IF NOT EXISTS restriction_release_rule VARCHAR(255),
  ADD COLUMN IF NOT EXISTS compliance_status VARCHAR(32) DEFAULT 'IN_GOOD_STANDING' NOT NULL,
  ADD COLUMN IF NOT EXISTS reporting_frequency VARCHAR(32),
  ADD COLUMN IF NOT EXISTS next_report_due DATE,
  ADD COLUMN IF NOT EXISTS closeout_date DATE,
  ADD COLUMN IF NOT EXISTS canonical_txn_id BIGINT,
  ADD COLUMN IF NOT EXISTS activity_id BIGINT,
  ADD COLUMN IF NOT EXISTS counterparty_id BIGINT,
  ADD COLUMN IF NOT EXISTS contact_person_id BIGINT,
  ADD COLUMN IF NOT EXISTS grant_reference_number VARCHAR(128),
  ADD COLUMN IF NOT EXISTS compliance_notes VARCHAR(2000);

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS ck_grant_record_restriction_class
  CHECK (restriction_class IN ('RESTRICTED','UNRESTRICTED','BOARD_DESIGNATED'));

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS ck_grant_record_compliance_status
  CHECK (compliance_status IN ('IN_GOOD_STANDING','LATE_REPORT','AT_RISK','SUSPENDED','CLOSED'));

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS ck_grant_record_period_order
  CHECK (
    period_start IS NULL
    OR period_end IS NULL
    OR period_start <= period_end
  );

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS ck_grant_record_award_amount_nonnegative
  CHECK (amount IS NULL OR amount >= 0);

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS ck_grant_record_contact_presence
  CHECK (
    donor_id IS NOT NULL
    OR person_id IS NOT NULL
    OR counterparty_id IS NOT NULL
    OR NULLIF(TRIM(grantor), '') IS NOT NULL
  );

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_donor
  FOREIGN KEY (donor_id) REFERENCES donor(id) ON DELETE SET NULL;

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_person
  FOREIGN KEY (person_id) REFERENCES person(id) ON DELETE SET NULL;

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_contact_person
  FOREIGN KEY (contact_person_id) REFERENCES person(id) ON DELETE SET NULL;

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_counterparty
  FOREIGN KEY (counterparty_id) REFERENCES counterparty(id) ON DELETE SET NULL;

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_fund
  FOREIGN KEY (fund_id) REFERENCES fund(id) ON DELETE SET NULL;

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_activity
  FOREIGN KEY (activity_id) REFERENCES activity(id) ON DELETE SET NULL;

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_legacy_txn
  FOREIGN KEY (journal_txn_id) REFERENCES journal_transaction(id) ON DELETE SET NULL;

ALTER TABLE grant_record
  ADD CONSTRAINT IF NOT EXISTS fk_grant_record_canonical_txn
  FOREIGN KEY (canonical_txn_id) REFERENCES txn(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_grant_record_reporting_due
  ON grant_record(compliance_status, next_report_due);

CREATE INDEX IF NOT EXISTS ix_grant_record_restriction_fund
  ON grant_record(restriction_class, fund_id);

CREATE INDEX IF NOT EXISTS ix_grant_record_activity
  ON grant_record(activity_id);

CREATE INDEX IF NOT EXISTS ix_grant_record_counterparty
  ON grant_record(counterparty_id);

CREATE UNIQUE INDEX IF NOT EXISTS uq_grant_record_reference_number
  ON grant_record(grant_reference_number);

-- 2) Create posting-level bridge for detailed traceability to ledger lines.
CREATE TABLE IF NOT EXISTS grant_posting_link(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grant_record_id VARCHAR(255) NOT NULL,
  posting_model VARCHAR(16) NOT NULL,
  txn_split_id BIGINT,
  journal_entry_id BIGINT,
  posting_role VARCHAR(16) DEFAULT 'REVENUE' NOT NULL,
  recognized_amount DECIMAL(19,2) NOT NULL,
  recognized_on DATE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE grant_posting_link
  ADD CONSTRAINT IF NOT EXISTS ck_grant_posting_model
  CHECK (posting_model IN ('CANONICAL','LEGACY'));

ALTER TABLE grant_posting_link
  ADD CONSTRAINT IF NOT EXISTS ck_grant_posting_role
  CHECK (posting_role IN ('REVENUE','DEFERRAL','RELEASE','ADJUSTMENT'));

ALTER TABLE grant_posting_link
  ADD CONSTRAINT IF NOT EXISTS ck_grant_posting_amount_nonzero
  CHECK (recognized_amount <> 0);

ALTER TABLE grant_posting_link
  ADD CONSTRAINT IF NOT EXISTS ck_grant_posting_target_xor
  CHECK (
    (txn_split_id IS NOT NULL AND journal_entry_id IS NULL)
    OR (txn_split_id IS NULL AND journal_entry_id IS NOT NULL)
  );

ALTER TABLE grant_posting_link
  ADD CONSTRAINT IF NOT EXISTS fk_grant_posting_grant
  FOREIGN KEY (grant_record_id) REFERENCES grant_record(grant_record_id) ON DELETE CASCADE;

ALTER TABLE grant_posting_link
  ADD CONSTRAINT IF NOT EXISTS fk_grant_posting_split
  FOREIGN KEY (txn_split_id) REFERENCES txn_split(id) ON DELETE CASCADE;

ALTER TABLE grant_posting_link
  ADD CONSTRAINT IF NOT EXISTS fk_grant_posting_entry
  FOREIGN KEY (journal_entry_id) REFERENCES journal_entry(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS ix_grant_posting_grant_role
  ON grant_posting_link(grant_record_id, posting_role, recognized_on);

CREATE INDEX IF NOT EXISTS ix_grant_posting_split
  ON grant_posting_link(txn_split_id);

CREATE INDEX IF NOT EXISTS ix_grant_posting_entry
  ON grant_posting_link(journal_entry_id);

-- 3) Provide a reference reporting view for restricted-vs-unrestricted balances.
CREATE OR REPLACE VIEW v_grant_restriction_reporting AS
SELECT
  gr.grant_record_id,
  gr.grant_id,
  gr.grant_reference_number,
  gr.status,
  gr.compliance_status,
  gr.restriction_class,
  f.code AS fund_code,
  f.name AS fund_name,
  a.code AS activity_code,
  a.name AS activity_name,
  COALESCE(d.name, p.name, cp.display_name, gr.grantor) AS donor_or_contact,
  gr.amount AS awarded_amount,
  COALESCE(pa.recognized_total, 0) AS recognized_amount,
  COALESCE(pa.deferred_total, 0) AS deferred_amount,
  (COALESCE(gr.amount, 0) - COALESCE(pa.recognized_total, 0)) AS unrecognized_balance,
  gr.next_report_due
FROM grant_record gr
LEFT JOIN donor d ON d.id = gr.donor_id
LEFT JOIN person p ON p.id = COALESCE(gr.contact_person_id, gr.person_id)
LEFT JOIN counterparty cp ON cp.id = gr.counterparty_id
LEFT JOIN fund f ON f.id = gr.fund_id
LEFT JOIN activity a ON a.id = gr.activity_id
LEFT JOIN (
  SELECT
    gpl.grant_record_id,
    SUM(CASE WHEN gpl.posting_role IN ('REVENUE','RELEASE') THEN gpl.recognized_amount ELSE 0 END) AS recognized_total,
    SUM(CASE WHEN gpl.posting_role = 'DEFERRAL' THEN gpl.recognized_amount ELSE 0 END) AS deferred_total
  FROM grant_posting_link gpl
  GROUP BY gpl.grant_record_id
) pa ON pa.grant_record_id = gr.grant_record_id;
