BEGIN;

CREATE TABLE IF NOT EXISTS alias_review_queue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alias_domain VARCHAR(20) NOT NULL,
  alias_id BIGINT,
  alias_text VARCHAR(400) NOT NULL,
  normalization_key VARCHAR(400) NOT NULL,
  candidate_count INT NOT NULL,
  candidate_ids VARCHAR(400),
  reason VARCHAR(200) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at TIMESTAMP,
  resolver VARCHAR(80),
  resolution_note VARCHAR(1000),
  CONSTRAINT chk_alias_review_queue_domain CHECK (alias_domain IN ('ACCOUNT','FUND')),
  CONSTRAINT chk_alias_review_queue_status CHECK (status IN ('OPEN','IN_PROGRESS','RESOLVED','REJECTED')),
  CONSTRAINT chk_alias_review_queue_candidate_count CHECK (candidate_count >= 0)
);

CREATE INDEX IF NOT EXISTS ix_alias_review_queue_status ON alias_review_queue(status, alias_domain);
CREATE INDEX IF NOT EXISTS ix_alias_review_queue_norm ON alias_review_queue(normalization_key, alias_domain);

ALTER TABLE account
  ADD CONSTRAINT IF NOT EXISTS chk_account_number_not_blank
  CHECK (LENGTH(TRIM(account_number)) > 0);

ALTER TABLE account
  ADD CONSTRAINT IF NOT EXISTS chk_account_name_not_blank
  CHECK (name IS NULL OR LENGTH(TRIM(name)) > 0);

ALTER TABLE account
  ADD CONSTRAINT IF NOT EXISTS chk_account_code_not_blank
  CHECK (code IS NULL OR LENGTH(TRIM(code)) > 0);

ALTER TABLE account
  ADD CONSTRAINT IF NOT EXISTS chk_account_active_date_range
  CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from);

CREATE UNIQUE INDEX IF NOT EXISTS uq_account_number_norm_active
  ON account(REPLACE(REPLACE(UPPER(TRIM(account_number)), '-', ''), ' ', ''))
  WHERE is_active = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_account_code_norm_active
  ON account(REPLACE(REPLACE(UPPER(TRIM(code)), '-', ''), ' ', ''))
  WHERE is_active = TRUE AND code IS NOT NULL;

ALTER TABLE fund
  ADD CONSTRAINT IF NOT EXISTS chk_fund_code_not_blank
  CHECK (LENGTH(TRIM(code)) > 0);

ALTER TABLE fund
  ADD CONSTRAINT IF NOT EXISTS chk_fund_name_not_blank
  CHECK (LENGTH(TRIM(name)) > 0);

ALTER TABLE fund
  ADD CONSTRAINT IF NOT EXISTS chk_fund_active_date_range
  CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fund_code_norm_active
  ON fund(REPLACE(REPLACE(UPPER(TRIM(code)), '-', ''), ' ', ''))
  WHERE is_active = TRUE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fund_name_norm_active
  ON fund(REPLACE(REPLACE(UPPER(TRIM(name)), '-', ''), ' ', ''))
  WHERE is_active = TRUE;

ALTER TABLE account_alias
  ADD CONSTRAINT IF NOT EXISTS chk_account_alias_text_not_blank
  CHECK (LENGTH(TRIM(alias_text)) > 0);

ALTER TABLE account_alias
  ADD CONSTRAINT IF NOT EXISTS fk_account_alias_account
  FOREIGN KEY (account_id) REFERENCES account(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_account_alias_norm_active
  ON account_alias(REPLACE(REPLACE(UPPER(TRIM(alias_text)), '-', ''), ' ', ''))
  WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS ix_account_alias_account_active
  ON account_alias(account_id, is_active);

ALTER TABLE fund_alias
  ADD CONSTRAINT IF NOT EXISTS chk_fund_alias_text_not_blank
  CHECK (LENGTH(TRIM(alias_text)) > 0);

ALTER TABLE fund_alias
  ADD CONSTRAINT IF NOT EXISTS fk_fund_alias_fund
  FOREIGN KEY (fund_id) REFERENCES fund(id) ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS uq_fund_alias_norm_active
  ON fund_alias(REPLACE(REPLACE(UPPER(TRIM(alias_text)), '-', ''), ' ', ''))
  WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS ix_fund_alias_fund_active
  ON fund_alias(fund_id, is_active);

INSERT INTO alias_review_queue(alias_domain, alias_id, alias_text, normalization_key, candidate_count, candidate_ids, reason)
SELECT 'ACCOUNT',
       MIN(aa.id) AS alias_id,
       MIN(aa.alias_text) AS alias_text,
       REPLACE(REPLACE(UPPER(TRIM(MIN(aa.alias_text))), '-', ''), ' ', '') AS normalization_key,
       COUNT(DISTINCT aa.account_id) AS candidate_count,
       LISTAGG(CAST(aa.account_id AS VARCHAR(32)), ',') WITHIN GROUP (ORDER BY aa.account_id) AS candidate_ids,
       'ACTIVE_ALIAS_COLLISION'
FROM account_alias aa
WHERE aa.is_active = TRUE
GROUP BY REPLACE(REPLACE(UPPER(TRIM(aa.alias_text)), '-', ''), ' ', '')
HAVING COUNT(DISTINCT aa.account_id) > 1
   AND NOT EXISTS (
       SELECT 1 FROM alias_review_queue q
       WHERE q.alias_domain = 'ACCOUNT'
         AND q.normalization_key = REPLACE(REPLACE(UPPER(TRIM(aa.alias_text)), '-', ''), ' ', '')
         AND q.reason = 'ACTIVE_ALIAS_COLLISION'
         AND q.status IN ('OPEN','IN_PROGRESS')
   );

INSERT INTO alias_review_queue(alias_domain, alias_id, alias_text, normalization_key, candidate_count, candidate_ids, reason)
SELECT 'FUND',
       MIN(fa.id) AS alias_id,
       MIN(fa.alias_text) AS alias_text,
       REPLACE(REPLACE(UPPER(TRIM(MIN(fa.alias_text))), '-', ''), ' ', '') AS normalization_key,
       COUNT(DISTINCT fa.fund_id) AS candidate_count,
       LISTAGG(CAST(fa.fund_id AS VARCHAR(32)), ',') WITHIN GROUP (ORDER BY fa.fund_id) AS candidate_ids,
       'ACTIVE_ALIAS_COLLISION'
FROM fund_alias fa
WHERE fa.is_active = TRUE
GROUP BY REPLACE(REPLACE(UPPER(TRIM(fa.alias_text)), '-', ''), ' ', '')
HAVING COUNT(DISTINCT fa.fund_id) > 1
   AND NOT EXISTS (
       SELECT 1 FROM alias_review_queue q
       WHERE q.alias_domain = 'FUND'
         AND q.normalization_key = REPLACE(REPLACE(UPPER(TRIM(fa.alias_text)), '-', ''), ' ', '')
         AND q.reason = 'ACTIVE_ALIAS_COLLISION'
         AND q.status IN ('OPEN','IN_PROGRESS')
   );

COMMIT;
