BEGIN;

CREATE TABLE IF NOT EXISTS config_release (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  release_code VARCHAR(64) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  effective_from DATE NOT NULL,
  effective_to DATE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(80) NOT NULL DEFAULT 'migration',
  approved_at TIMESTAMP,
  approved_by VARCHAR(80),
  notes VARCHAR(1000),
  CONSTRAINT uq_config_release_code UNIQUE (release_code),
  CONSTRAINT chk_config_release_status CHECK (status IN ('DRAFT','APPROVED','ACTIVE','RETIRED')),
  CONSTRAINT chk_config_release_dates CHECK (effective_to IS NULL OR effective_to >= effective_from)
);

CREATE TABLE IF NOT EXISTS statement_section (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_release_id BIGINT NOT NULL,
  report_type VARCHAR(40) NOT NULL,
  section_code VARCHAR(80) NOT NULL,
  section_name VARCHAR(200) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(80) NOT NULL DEFAULT 'migration',
  CONSTRAINT fk_statement_section_release
    FOREIGN KEY (config_release_id) REFERENCES config_release(id) ON DELETE CASCADE,
  CONSTRAINT chk_statement_section_report_type CHECK (report_type IN ('INCOME_STATEMENT','BALANCE_SHEET','SCHEDULE','CUSTOM')),
  CONSTRAINT chk_statement_section_code_not_blank CHECK (LENGTH(TRIM(section_code)) > 0),
  CONSTRAINT chk_statement_section_name_not_blank CHECK (LENGTH(TRIM(section_name)) > 0),
  CONSTRAINT uq_statement_section_release_code UNIQUE (config_release_id, report_type, section_code)
);

CREATE TABLE IF NOT EXISTS account_statement_mapping (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_release_id BIGINT NOT NULL,
  account_id BIGINT NOT NULL,
  statement_section_id BIGINT NOT NULL,
  sign_policy VARCHAR(20) NOT NULL,
  sort_order INT NOT NULL DEFAULT 0,
  valid_from DATE NOT NULL,
  valid_to DATE,
  source VARCHAR(80) NOT NULL DEFAULT 'LEGACY_MIGRATION',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(80) NOT NULL DEFAULT 'migration',
  change_reason VARCHAR(1000),
  CONSTRAINT fk_asm_release FOREIGN KEY (config_release_id) REFERENCES config_release(id) ON DELETE CASCADE,
  CONSTRAINT fk_asm_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_asm_section FOREIGN KEY (statement_section_id) REFERENCES statement_section(id),
  CONSTRAINT chk_asm_sign_policy CHECK (sign_policy IN ('NORMAL','INVERT')),
  CONSTRAINT chk_asm_dates CHECK (valid_to IS NULL OR valid_to >= valid_from),
  CONSTRAINT uq_asm_open_row UNIQUE (config_release_id, account_id, statement_section_id, valid_from)
);

CREATE TABLE IF NOT EXISTS schedule_requirement_rule (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_release_id BIGINT NOT NULL,
  subject_kind VARCHAR(20) NOT NULL,
  account_id BIGINT,
  subtype VARCHAR(40),
  schedule_kind_id BIGINT NOT NULL,
  requirement_level VARCHAR(20) NOT NULL,
  valid_from DATE NOT NULL,
  valid_to DATE,
  precedence SMALLINT NOT NULL DEFAULT 100,
  source VARCHAR(80) NOT NULL DEFAULT 'LEGACY_MIGRATION',
  rationale VARCHAR(1000),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(80) NOT NULL DEFAULT 'migration',
  CONSTRAINT fk_srr_release FOREIGN KEY (config_release_id) REFERENCES config_release(id) ON DELETE CASCADE,
  CONSTRAINT fk_srr_account FOREIGN KEY (account_id) REFERENCES account(id),
  CONSTRAINT fk_srr_schedule_kind FOREIGN KEY (schedule_kind_id) REFERENCES schedule_kind(id),
  CONSTRAINT chk_srr_subject_kind CHECK (subject_kind IN ('ACCOUNT','SUBTYPE')),
  CONSTRAINT chk_srr_subject_ref CHECK (
    (subject_kind = 'ACCOUNT' AND account_id IS NOT NULL AND subtype IS NULL)
    OR
    (subject_kind = 'SUBTYPE' AND account_id IS NULL AND subtype IS NOT NULL)
  ),
  CONSTRAINT chk_srr_req_level CHECK (requirement_level IN ('REQUIRED','OPTIONAL','EXCLUDED')),
  CONSTRAINT chk_srr_dates CHECK (valid_to IS NULL OR valid_to >= valid_from)
);

CREATE INDEX IF NOT EXISTS ix_statement_section_release_type
  ON statement_section(config_release_id, report_type, sort_order, id);

CREATE INDEX IF NOT EXISTS ix_asm_account_open
  ON account_statement_mapping(account_id, valid_to, config_release_id);

CREATE INDEX IF NOT EXISTS ix_asm_release_account_validity
  ON account_statement_mapping(config_release_id, account_id, valid_to);

CREATE INDEX IF NOT EXISTS ix_srr_subject_lookup
  ON schedule_requirement_rule(subject_kind, account_id, subtype, valid_to, precedence);

CREATE INDEX IF NOT EXISTS ix_srr_release_account_schedule_validity
  ON schedule_requirement_rule(config_release_id, subject_kind, account_id, schedule_kind_id, valid_to);

CREATE INDEX IF NOT EXISTS ix_srr_release_subtype_schedule_validity
  ON schedule_requirement_rule(config_release_id, subject_kind, subtype, schedule_kind_id, valid_to);

CREATE TABLE IF NOT EXISTS config_change_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  config_release_id BIGINT NOT NULL,
  entity_name VARCHAR(80) NOT NULL,
  entity_pk VARCHAR(120) NOT NULL,
  operation VARCHAR(20) NOT NULL,
  changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  changed_by VARCHAR(80) NOT NULL DEFAULT 'system',
  reason VARCHAR(1000),
  old_value_json CLOB,
  new_value_json CLOB,
  CONSTRAINT fk_cce_release FOREIGN KEY (config_release_id) REFERENCES config_release(id) ON DELETE CASCADE,
  CONSTRAINT chk_cce_operation CHECK (operation IN ('INSERT','UPDATE','DELETE'))
);

MERGE INTO config_release (release_code, status, effective_from, notes)
KEY (release_code)
VALUES ('LEGACY_BASELINE_V1', 'ACTIVE', CURRENT_DATE, 'Backfilled baseline from legacy reporting/schedule tables.');

INSERT INTO statement_section (config_release_id, report_type, section_code, section_name, sort_order, created_by)
SELECT cr.id,
       rs.report_type,
       UPPER(REPLACE(TRIM(rs.name), ' ', '_')),
       rs.name,
       rs.sort_order,
       'migration'
FROM report_section rs
JOIN config_release cr ON cr.release_code = 'LEGACY_BASELINE_V1'
WHERE NOT EXISTS (
  SELECT 1
  FROM statement_section ss
  WHERE ss.config_release_id = cr.id
    AND ss.report_type = rs.report_type
    AND ss.section_code = UPPER(REPLACE(TRIM(rs.name), ' ', '_'))
);

INSERT INTO account_statement_mapping (
  config_release_id,
  account_id,
  statement_section_id,
  sign_policy,
  sort_order,
  valid_from,
  valid_to,
  source,
  created_by,
  change_reason
)
SELECT cr.id,
       ars.account_id,
       ss.id,
       ars.sign_policy,
       ars.sort_order,
       CURRENT_DATE,
       NULL,
       'LEGACY_MIGRATION',
       'migration',
       'Baseline backfill from account_report_section'
FROM account_report_section ars
JOIN report_section rs ON rs.id = ars.report_section_id
JOIN config_release cr ON cr.release_code = 'LEGACY_BASELINE_V1'
JOIN statement_section ss
  ON ss.config_release_id = cr.id
 AND ss.report_type = rs.report_type
 AND ss.section_code = UPPER(REPLACE(TRIM(rs.name), ' ', '_'))
WHERE NOT EXISTS (
  SELECT 1
  FROM account_statement_mapping asm
  WHERE asm.config_release_id = cr.id
    AND asm.account_id = ars.account_id
    AND asm.statement_section_id = ss.id
    AND asm.valid_to IS NULL
);

INSERT INTO schedule_requirement_rule (
  config_release_id,
  subject_kind,
  account_id,
  subtype,
  schedule_kind_id,
  requirement_level,
  valid_from,
  valid_to,
  precedence,
  source,
  rationale,
  created_by
)
SELECT cr.id,
       'ACCOUNT',
       asr.account_id,
       NULL,
       asr.schedule_kind_id,
       CASE WHEN asr.is_required THEN 'REQUIRED' ELSE 'OPTIONAL' END,
       CURRENT_DATE,
       NULL,
       10,
       'LEGACY_MIGRATION',
       COALESCE(asr.notes, 'Baseline backfill from account_schedule_requirement'),
       'migration'
FROM account_schedule_requirement asr
JOIN config_release cr ON cr.release_code = 'LEGACY_BASELINE_V1'
WHERE NOT EXISTS (
  SELECT 1
  FROM schedule_requirement_rule srr
  WHERE srr.config_release_id = cr.id
    AND srr.subject_kind = 'ACCOUNT'
    AND srr.account_id = asr.account_id
    AND srr.schedule_kind_id = asr.schedule_kind_id
    AND srr.valid_to IS NULL
);

INSERT INTO schedule_requirement_rule (
  config_release_id,
  subject_kind,
  account_id,
  subtype,
  schedule_kind_id,
  requirement_level,
  valid_from,
  valid_to,
  precedence,
  source,
  rationale,
  created_by
)
SELECT cr.id,
       'SUBTYPE',
       NULL,
       assd.subtype,
       assd.schedule_kind_id,
       'REQUIRED',
       CURRENT_DATE,
       NULL,
       100,
       'LEGACY_MIGRATION',
       'Baseline backfill from account_subtype_schedule_default',
       'migration'
FROM account_subtype_schedule_default assd
JOIN config_release cr ON cr.release_code = 'LEGACY_BASELINE_V1'
WHERE NOT EXISTS (
  SELECT 1
  FROM schedule_requirement_rule srr
  WHERE srr.config_release_id = cr.id
    AND srr.subject_kind = 'SUBTYPE'
    AND srr.subtype = assd.subtype
    AND srr.schedule_kind_id = assd.schedule_kind_id
    AND srr.valid_to IS NULL
);

COMMIT;
