# Generated metadata for Jasper report bundle
displayName=Income 4
generatorClass=nonprofitbookkeeping.reports.jasper.Income4JasperGenerator
reportType=SCA_INCOME_4_JASPER
template=INCOME_4.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.Income4Bean
description=Income schedule 4. Data bean: Income4Bean.
