# Generated metadata for Jasper report bundle
displayName=Chart Of Accounts
generatorClass=nonprofitbookkeeping.reports.jasper.ChartOfAccountsJasperGenerator
reportType=CHART_OF_ACCOUNTS_JASPER
template=ChartOfAccountsAlt.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.ChartOfAccountsRowBean
description=Chart of accounts listing. Data bean: ChartOfAccountsRowBean.
beanName=chartOfAccountsRow
