# Generated metadata for Jasper report bundle
displayName=Expense Detail 12a
generatorClass=nonprofitbookkeeping.reports.jasper.ExpenseDtl12aJasperGenerator
reportType=SCA_EXPENSE_DTL_12A_JASPER
template=EXPENSE_DTL_12a.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.ExpenseDtl12aBean
beanName=ExpenseDtl12aBean
description=Expense detail schedule 12a. Data bean: ExpenseDtl12aBean.
beanName=expenseDtl12a
