# Generated metadata for Jasper report bundle
displayName=Income Detail 11a
generatorClass=nonprofitbookkeeping.reports.jasper.IncomeDtl11aJasperGenerator
reportType=SCA_INCOME_DTL_11A_JASPER
template=INCOME_DTL_11a.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.IncomeDtl11aBean
beanName=IncomeDtl11aBean
description=Income detail schedule 11a. Data bean: IncomeDtl11aBean.
beanName=incomeDtl11a
