# Mapping of report row identifiers to bean and panel classes
# format: id=beanClass,panelClass
sca_regalia_sales_dtl_7_jasper=nonprofitbookkeeping.reports.datasource.scareports.RegaliaSalesDtl7Bean,nonprofitbookkeeping.ui.panels.scareports.RegaliaSalesPanelFX
