package org.nonprofitbookkeeping.repository;

import org.flywaydb.core.Flyway;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.UUID;

/**
 * Shared in-memory DB setup for repository tests.
 */
public final class RepositoryIntegrationSupport
{
    private RepositoryIntegrationSupport()
    {
    }

    public static DataSource migratedDataSource()
    {
        String dbName = "repo_test_" + UUID.randomUUID();
        String url = "jdbc:h2:mem:" + dbName + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1";
        DataSource ds = new TestDataSource(url, "sa", "");

        Flyway.configure()
                .dataSource(ds)
                .locations("classpath:db/migration")
                .load()
                .migrate();

        ensureRepositorySchema(ds);
        return ds;
    }

    private static void ensureRepositorySchema(DataSource ds)
    {
        String ddl = """
                CREATE TABLE IF NOT EXISTS approval_audit_record (
                    id UUID PRIMARY KEY,
                    group_code VARCHAR(128) NOT NULL,
                    workflow_type VARCHAR(64) NOT NULL,
                    workflow_run_id UUID NULL,
                    decision VARCHAR(16) NOT NULL CHECK (decision IN ('APPROVED','REJECTED','ESCALATED')),
                    actor VARCHAR(256) NOT NULL,
                    rationale VARCHAR(1024) NULL,
                    created_at TIMESTAMP NOT NULL
                );

                CREATE TABLE IF NOT EXISTS journal_transaction (
                    id UUID PRIMARY KEY,
                    group_code VARCHAR(128) NOT NULL,
                    posted_on DATE NOT NULL,
                    memo VARCHAR(1024) NOT NULL,
                    bank_timing VARCHAR(32) NOT NULL,
                    budget_timing VARCHAR(32) NOT NULL,
                    reversed_transaction_id UUID NULL
                );

                CREATE TABLE IF NOT EXISTS journal_posting_line (
                    transaction_id UUID NOT NULL,
                    line_order INT NOT NULL,
                    account_code VARCHAR(128) NOT NULL,
                    fund_code VARCHAR(128) NOT NULL,
                    entry_side VARCHAR(16) NOT NULL CHECK (entry_side IN ('DEBIT','CREDIT')),
                    amount DECIMAL(18,2) NOT NULL,
                    PRIMARY KEY (transaction_id, line_order),
                    CONSTRAINT fk_journal_posting_line_transaction
                      FOREIGN KEY (transaction_id) REFERENCES journal_transaction(id) ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS reconciliation_run (
                    id UUID PRIMARY KEY,
                    group_code VARCHAR(128) NOT NULL,
                    statement_ending_on DATE NOT NULL,
                    bank_format VARCHAR(8) NOT NULL CHECK (bank_format IN ('OFX','QFX')),
                    imported_transaction_count INT NOT NULL,
                    status VARCHAR(16) NOT NULL CHECK (status IN ('STARTED','COMPLETED','FAILED')),
                    notes VARCHAR(1024) NULL
                );

                CREATE TABLE IF NOT EXISTS period_close_run (
                    id UUID PRIMARY KEY,
                    group_code VARCHAR(128) NOT NULL,
                    close_date DATE NOT NULL,
                    status VARCHAR(16) NOT NULL CHECK (status IN ('STARTED','COMPLETED','FAILED')),
                    produced_transaction_id UUID NULL,
                    notes VARCHAR(1024) NULL
                );

                CREATE TABLE IF NOT EXISTS open_item_snapshot (
                    id UUID PRIMARY KEY,
                    group_code VARCHAR(128) NOT NULL,
                    item_kind VARCHAR(64) NOT NULL,
                    item_ref VARCHAR(256) NOT NULL,
                    state VARCHAR(64) NOT NULL,
                    original_amount DECIMAL(18,2) NOT NULL,
                    open_amount DECIMAL(18,2) NOT NULL,
                    last_transaction_id UUID NULL,
                    last_updated_on DATE NOT NULL,
                    version BIGINT NOT NULL,
                    CONSTRAINT uq_open_item_snapshot_natural UNIQUE (group_code, item_kind, item_ref)
                );

                CREATE TABLE IF NOT EXISTS open_item_transition (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    snapshot_id UUID NOT NULL,
                    transition_on DATE NOT NULL,
                    from_state VARCHAR(64) NOT NULL,
                    to_state VARCHAR(64) NOT NULL,
                    trigger_transaction_id UUID NULL,
                    notes VARCHAR(1024) NULL,
                    CONSTRAINT fk_open_item_transition_snapshot
                      FOREIGN KEY (snapshot_id) REFERENCES open_item_snapshot(id) ON DELETE CASCADE
                );
                """;

        try (Connection c = ds.getConnection();
             Statement statement = c.createStatement())
        {
            for (String sql : ddl.split(";\\s*\\n"))
            {
                String trimmed = sql.trim();
                if (!trimmed.isEmpty())
                {
                    statement.execute(trimmed);
                }
            }
        }
        catch (Exception ex)
        {
            throw new IllegalStateException("Could not initialize repository test schema", ex);
        }
    }
}
