# Generated metadata for Jasper report bundle
displayName=Transfer Out 10
generatorClass=nonprofitbookkeeping.reports.jasper.TransferOut10JasperGenerator
reportType=SCA_TRANSFER_OUT_10_JASPER
template=TRANSFER_OUT_10.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.TransferOut10Bean
description=Transfer out schedule 10. Data bean: TransferOut10Bean.
