# Generated metadata for Jasper report bundle
displayName=Inventory Detail 6
generatorClass=nonprofitbookkeeping.reports.jasper.InventoryDtl6JasperGenerator
reportType=SCA_INVENTORY_DTL_6_JASPER
template=INVENTORY_DTL_6.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.InventoryDtl6Bean
beanName=InventoryDtl6Bean
description=Inventory detail schedule 6. Data bean: InventoryDtl6Bean.
