# Generated metadata for Jasper report bundle
displayName=Income Detail 11c
generatorClass=nonprofitbookkeeping.reports.jasper.IncomeDtl11cJasperGenerator
reportType=SCA_INCOME_DTL_11C_JASPER
template=INCOME_DTL_11c.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.IncomeDtl11cBean
beanName=IncomeDtl11cBean
description=Income detail schedule 11c. Data bean: IncomeDtl11cBean.
