# Generated metadata for Jasper report bundle
displayName=Liability Detail 5b
generatorClass=nonprofitbookkeeping.reports.jasper.LiabilityDtl5bJasperGenerator
reportType=SCA_LIABILITY_DTL_5B_JASPER
template=LIABILITY_DTL_5b.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.LiabilityDtl5bBean
beanName=LiabilityDtl5bBean
description=Liability detail schedule 5b. Data bean: LiabilityDtl5bBean.
beanName=liabilityDtl5b
