# Generated metadata for Jasper report bundle
displayName=Funds 14
generatorClass=nonprofitbookkeeping.reports.jasper.Funds14JasperGenerator
reportType=SCA_FUNDS_14_JASPER
template=FUNDS_14.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.Funds14Bean
description=Funds summary schedule 14. Data bean: Funds14Bean.
