# Generated metadata for Jasper report bundle
displayName=Regalia Sales Detail 7
generatorClass=nonprofitbookkeeping.reports.jasper.RegaliaSalesDtl7JasperGenerator
reportType=SCA_REGALIA_SALES_DTL_7_JASPER
template=REGALIA_SALES_DTL_7.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.RegaliaSalesDtl7Bean
description=Regalia sales detail schedule 7. Data bean: RegaliaSalesDtl7Bean.
beanName=regaliaSalesDtl7
