
package nonprofitbookkeeping.service;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import nonprofitbookkeeping.ui.helpers.AlertBox;


/**
 * DocumentStorageService manages attachment and retrieval of document files
 * associated with transactions.
 * <p>
 * Documents are stored in a designated directory on disk (in the user's home
 * directory, under "NonprofitDocuments"). The attach method copies files into that
 * directory and assigns a unique filename based on transaction ID and timestamp.
 * </p>
 */
public class DocumentStorageService
{
	
	/** The Constant LOGGER. */
	private static final Logger LOGGER =
		LoggerFactory.getLogger(DocumentStorageService.class);
	
	/** Base directory located in the user's home directory under "NonprofitDocuments" for storing all attached documents. */
	private static final File DOCUMENT_BASE_DIR =
		new File(System.getProperty("user.home"), "NonprofitDocuments");
	
	/**
	 * Static initializer block to ensure that the base directory for document storage
	 * ({@link #DOCUMENT_BASE_DIR}) exists when the class is loaded.
	 * If the directory does not exist, it will be created.
	 */
	static
	{
		
		if (!DOCUMENT_BASE_DIR.exists())
		{
			DOCUMENT_BASE_DIR.mkdirs();
		}
		
	}
	
	/**
	 * Attaches a specified document file to a transaction.
	 * The method copies the source {@code file} into a predefined storage directory
	 * ({@link #DOCUMENT_BASE_DIR}). The copied file is renamed using the {@code transactionId},
	 * a timestamp to ensure uniqueness, and the original file's extension.
	 * This new filename effectively becomes the document's unique identifier within the storage.
	 * If a file with the generated name already exists, it will be replaced.
	 *
	 * @param transactionId The ID of the transaction to which the document should be attached.
	 *                      This is used in generating the stored filename. Must not be null or empty.
	 * @param file The source {@link File} to be attached. Must not be null and must exist.
	 * @throws IOException if an error occurs during file copying (e.g., permission issues, disk full).
	 * @throws IllegalArgumentException if {@code file} is null or does not exist, or if {@code transactionId} is null or empty.
	 */
	public void attachDocumentToTransaction(String transactionId, File file)
		throws IOException
	{
		
		if (transactionId == null || transactionId.trim().isEmpty())
		{
			throw new IllegalArgumentException(
				"Transaction ID must not be null or empty.");
		}
		
		if (file == null || !file.exists())
		{
			throw new IllegalArgumentException("File does not exist: " + file);
		}
		
		// Get the original file's extension (if any).
		String originalName = file.getName();
		String extension = "";
		int idx = originalName.lastIndexOf('.');
		
		if (idx > 0)
		{
			extension = originalName.substring(idx);
		}
		
		// Generate a new filename using the transactionId and the current
		// timestamp.
		String newFileName =
			transactionId + "_" + System.currentTimeMillis() + extension;
		File targetFile = new File(DOCUMENT_BASE_DIR, newFileName);
		
		try
		{
			// Copy the source file to the target location, replacing any
			// existing file.
			Files.copy(file.toPath(), targetFile.toPath(),
				StandardCopyOption.REPLACE_EXISTING);
			LOGGER.info("Document attached for transaction {}: {}",
				transactionId,
				targetFile.getAbsolutePath());
		}
		catch (IOException e)
		{
			LOGGER.error("Failed to attach document for transaction {}",
				transactionId, e);
			AlertBox.showError(null,
				"Failed to attach document: " + e.getMessage());
			throw e;
		}
		
	}
	
	/**
	 * Retrieves a document from the storage directory based on its document ID.
	 * The {@code documentId} is expected to be the filename under which the document
	 * was stored (typically generated by {@link #attachDocumentToTransaction(String, File)}).
	 *
	 * @param documentId The unique identifier (filename) of the document to retrieve. Must not be null or empty.
	 * @return A {@link File} object pointing to the stored document.
	 * @throws IOException if the document identified by {@code documentId} is not found in the storage directory,
	 *                     or if there's an issue accessing it.
	 * @throws IllegalArgumentException if {@code documentId} is null or empty.
	 */
	public File retrieveDocument(String documentId) throws IOException
	{
		
		if (documentId == null || documentId.trim().isEmpty())
		{
			throw new IllegalArgumentException(
				"Document ID must not be empty.");
		}
		
		File targetFile = new File(DOCUMENT_BASE_DIR, documentId);
		
		if (!targetFile.exists())
		{
			throw new IOException("Document not found: " + documentId);
		}
		
		return targetFile;
		
	}
	
}
