# Generated metadata for Jasper report bundle
displayName=Contact Info 1
generatorClass=nonprofitbookkeeping.reports.jasper.ContactInfoJasperGenerator
reportType=SCA_CONTACT_INFO_JASPER
template=CONTACT_INFO_1.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.ContactInfoBean
beanName=ContactInfoBean
description=SCA contact information sheet. Data bean: ContactInfoBean.
beanName=contactInfo
