package nonprofitbookkeeping.reports.runtime;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;
import java.time.LocalDate;
import java.util.Map;

/**
 * Reflection-based helper that populates a bean from a Map of fieldName -> value.
 *
 * Field naming convention:
 *   - Map key:   "cashamount" or "total_assets"
 *   - Setter:    setCashamount(...), setTotal_assets(...)
 *
 * This matches the beans generated by your Excelâ†’JRXML/bean generator
 * (sanitized field names, lowercased, underscores preserved).
 */
public final class DataFiller {

    private DataFiller() {
    }

    /**
     * Create a new instance of the given beanClass and populate it from the Map.
     *
     * @param beanClass type to instantiate
     * @param values    map of fieldName -> value
     * @return populated bean instance
     * @throws IllegalStateException if instantiation or filling fails
     */
    public static <T> T fill(Class<T> beanClass, Map<String, ?> values) {
        try {
            T bean = beanClass.getDeclaredConstructor().newInstance();

            if (values == null || values.isEmpty()) {
                return bean;
            }

            Method[] methods = beanClass.getMethods();

            for (Map.Entry<String, ?> e : values.entrySet()) {
                String fieldName = e.getKey();
                Object value = e.getValue();

                if (fieldName == null || fieldName.isBlank()) {
                    continue;
                }
                if (value == null) {
                    continue;
                }

                String setterName = "set" + capitalize(fieldName);

                Method setter = findSetter(methods, setterName);
                if (setter == null) {
                    // No matching setter; skip
                    continue;
                }

                Class<?> paramType = setter.getParameterTypes()[0];
                Object converted = convertValue(value, paramType);
                if (converted == null && value != null) {
                    // Could not convert; skip rather than throwing
                    continue;
                }

                setter.invoke(bean, converted);
            }

            return bean;
        } catch (Exception ex) {
            throw new IllegalStateException(
                "Failed to fill bean of type " + beanClass.getName(), ex);
        }
    }

    private static Method findSetter(Method[] methods, String setterName) {
        for (Method m : methods) {
            if (!m.getName().equals(setterName)) {
                continue;
            }
            if (!Modifier.isPublic(m.getModifiers())) {
                continue;
            }
            if (m.getParameterCount() != 1) {
                continue;
            }
            return m;
        }
        return null;
    }

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) {
            return s;
        }
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    /**
     * Best-effort type conversion from JDBC/Map values to bean property type.
     */
    private static Object convertValue(Object value, Class<?> targetType) {
        if (value == null) {
            return null;
        }

        if (targetType.isInstance(value)) {
            return value;
        }

        // BigDecimal
        if (targetType == BigDecimal.class) {
            if (value instanceof BigDecimal) {
                return value;
            }
            if (value instanceof Number n) {
                return BigDecimal.valueOf(n.doubleValue());
            }
            if (value instanceof String s) {
                try {
                    return new BigDecimal(s);
                } catch (NumberFormatException ignored) {
                }
            }
        }

        // Integer / int
        if (targetType == Integer.class || targetType == int.class) {
            if (value instanceof Number n) {
                return n.intValue();
            }
            if (value instanceof String s) {
                try {
                    return Integer.parseInt(s);
                } catch (NumberFormatException ignored) {
                }
            }
        }

        // Long / long
        if (targetType == Long.class || targetType == long.class) {
            if (value instanceof Number n) {
                return n.longValue();
            }
            if (value instanceof String s) {
                try {
                    return Long.parseLong(s);
                } catch (NumberFormatException ignored) {
                }
            }
        }

        // Double / double
        if (targetType == Double.class || targetType == double.class) {
            if (value instanceof Number n) {
                return n.doubleValue();
            }
            if (value instanceof String s) {
                try {
                    return Double.parseDouble(s);
                } catch (NumberFormatException ignored) {
                }
            }
        }

        // Boolean / boolean
        if (targetType == Boolean.class || targetType == boolean.class) {
            if (value instanceof Boolean) {
                return value;
            }
            if (value instanceof String s) {
                return Boolean.parseBoolean(s);
            }
        }

        // String
        if (targetType == String.class) {
            return value.toString();
        }

        // LocalDate from SQL types
        if (targetType == LocalDate.class) {
            if (value instanceof Date d) {
                return d.toLocalDate();
            }
            if (value instanceof Timestamp ts) {
                return ts.toLocalDateTime().toLocalDate();
            }
        }

        // Fallback
        if (targetType.isAssignableFrom(value.getClass())) {
            return value;
        }

        return null;
    }
}
