# Generated metadata for Jasper report bundle
displayName=Asset Dtl 5a
generatorClass=nonprofitbookkeeping.reports.jasper.generator.ASSET_DTL_5aJasperGenerator
reportType=ASSET_DTL_5A_JASPER
template=ASSET_DTL_5a.jrxml
beanClass=nonprofitbookkeeping.reports.jasper.beans.AssetDtl5aReportBean
beanName=AssetDtl5aReportBean
description=Asset Dtl 5a. Data bean: AssetDtl5aReportBean.
