# Generated metadata for Jasper report bundle
displayName=Comments
generatorClass=nonprofitbookkeeping.reports.jasper.COMMENTSJasperGenerator
reportType=COMMENTS_JASPER
template=COMMENTS.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.COMMENTSBean
description=Comments. Data bean: COMMENTSBean.
