# Generated metadata for Jasper report bundle
displayName=Undeposited Funds Report
generatorClass=nonprofitbookkeeping.reports.jasper.generator.UNDEPOSITED_FUNDSJasperGenerator
reportType=UNDEPOSITED_FUNDS_JASPER
template=UNDEPOSITED_FUNDS.jrxml
beanClass=nonprofitbookkeeping.model.UndepositedFundsItem
beanName=UndepositedFundsItem
description=Undeposited Funds table output report.
