
package nonprofitbookkeeping.tools;

import nonprofitbookkeeping.core.Database;

import java.io.IOException;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Imports company data that has been exported as a standard H2 SQL script.
 * <p>
 * The script is expected to have been produced by the dedicated migration
 * utility that converts legacy <code>.npbk</code> archives into H2 scripts.
 * It can therefore contain <code>DROP</code>, <code>CREATE</code>, and
 * <code>INSERT</code> statements that fully hydrate the database. The method
 * executes the script contents through JDBC.
 */
public final class H2ScriptCompanyImporter
{

	private H2ScriptCompanyImporter()
	{

	}

	/**
	 * Import the provided SQL script into the currently open H2 database.
	 *
	 * @param scriptFile Path to the SQL script generated by the migration tool.
	 * @throws IOException  if the script cannot be read.
	 * @throws SQLException if the script execution fails.
	 */
	public static void importScript(Path scriptFile)
		throws IOException, SQLException
	{

		if (scriptFile == null)
		{
			throw new IllegalArgumentException("scriptFile cannot be null");
		}

		if (!Files.exists(scriptFile))
		{
			throw new IOException(
				"Script not found: " + scriptFile.toAbsolutePath());
		}

		try (Connection connection = Database.get().getConnection();
			Reader reader =
				Files.newBufferedReader(scriptFile, StandardCharsets.UTF_8))
		{
			StringBuilder sql = new StringBuilder();
			char[] buffer = new char[4096];
			int read;
			while ((read = reader.read(buffer)) != -1)
			{
				sql.append(buffer, 0, read);
			}

			try (Statement statement = connection.createStatement())
			{
				statement.execute(sql.toString());
			}
		}

	}

}
