# Generated metadata for Jasper report bundle
displayName=Finance Committee 13
generatorClass=nonprofitbookkeeping.reports.jasper.FinanceComm13JasperGenerator
reportType=SCA_FINANCE_COMM_13_JASPER
template=FINANCE_COMM_13.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.FinanceComm13Bean
beanName=FinanceComm13Bean
description=Finance committee schedule 13. Data bean: FinanceComm13Bean.
beanName=financeComm13
