#!/usr/bin/env python3
"""
Remove duplicate fund-transfer integrity table-shape Java DDL from Database.ensureSchema().

This helper applies the first conservative removal slice after the
EnsureSchemaFundTransferIntegrityCompatibilityValidationTest guard. It removes
only exact CREATE TABLE blocks from ensureFundTransferIntegrityArtifacts(). It
intentionally leaves the status-transition MERGE seed, foreign-key repair, and
index statements in place for separate review.

The script fails closed if the expected source text is not found.
"""

from __future__ import annotations

from pathlib import Path
import sys

DATABASE_PATH = Path("src/main/java/nonprofitbookkeeping/core/Database.java")

BLOCKS_TO_REMOVE = [
    """\t\tst.execute(\"\"\"
\t\t\t    CREATE TABLE IF NOT EXISTS fund_transfer_status_transition (
\t\t\t      from_status VARCHAR(20) NOT NULL,
\t\t\t      to_status VARCHAR(20) NOT NULL,
\t\t\t      is_allowed BOOLEAN NOT NULL,
\t\t\t      notes VARCHAR(300),
\t\t\t      PRIMARY KEY (from_status, to_status)
\t\t\t    )
\t\t\t\"\"\");
""",
    """\t\tst.execute(\"\"\"
\t\t\t    CREATE TABLE IF NOT EXISTS fund_transfer_integrity_event(
\t\t\t      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
\t\t\t      transfer_id BIGINT NOT NULL,
\t\t\t      event_type VARCHAR(40) NOT NULL,
\t\t\t      event_detail VARCHAR(1000),
\t\t\t      detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
\t\t\t    )
\t\t\t\"\"\");
""",
    """\t\tst.execute(\"\"\"
\t\t\t    CREATE TABLE IF NOT EXISTS fund_transfer_repair_queue(
\t\t\t      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
\t\t\t      transfer_id BIGINT NOT NULL,
\t\t\t      issue_code VARCHAR(60) NOT NULL,
\t\t\t      issue_detail VARCHAR(1000),
\t\t\t      proposed_action VARCHAR(500),
\t\t\t      detected_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
\t\t\t      resolved_at TIMESTAMP,
\t\t\t      resolved_by VARCHAR(120),
\t\t\t      resolution_note VARCHAR(1000)
\t\t\t    )
\t\t\t\"\"\");
""",
]


def main() -> int:
    if not DATABASE_PATH.exists():
        print(f"ERROR: {DATABASE_PATH} not found; run from the repository root.", file=sys.stderr)
        return 2

    original = DATABASE_PATH.read_text(encoding="utf-8")
    updated = original

    missing = []
    for block in BLOCKS_TO_REMOVE:
        if block not in updated:
            missing.append(block.splitlines()[0] if block.splitlines() else "<empty block>")
        else:
            updated = updated.replace(block, "", 1)

    if missing:
        print("ERROR: expected fund-transfer integrity DDL text was not found.", file=sys.stderr)
        for item in missing:
            print(f"  missing near: {item}", file=sys.stderr)
        return 3

    if updated == original:
        print("ERROR: no changes were made.", file=sys.stderr)
        return 4

    DATABASE_PATH.write_text(updated, encoding="utf-8")
    print("Removed duplicate fund-transfer integrity Java table-shape DDL.")
    print("Left status-transition seed, FK repair, and index statements for separate review.")
    print("Next: run focused schema tests and inspect the git diff.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
