# Generated metadata for Jasper report bundle
displayName=Income Statement Alt
generatorClass=nonprofitbookkeeping.reports.jasper.IncomeStatementAltJasperGenerator
reportType=INCOME_STATEMENT_ALT_JASPER
template=IncomeStatementAlt.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.IncomeStatementAltRowBean
description=Alternate income statement view. Data bean: IncomeStatementAltRowBean.
beanName=incomeStatementAltRow
