# Generated metadata for Jasper report bundle
displayName=Ledger Q1
generatorClass=nonprofitbookkeeping.reports.jasper.LedgerQ1JasperGenerator
reportType=SCA_LEDGER_Q1_JASPER
template=Ledger_Q1.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.LedgerQ1Bean
beanName=LedgerQ1Bean
description=Ledger Q1 schedule. Data bean: LedgerQ1Bean.
