package nonprofitbookkeeping.reports.datasource.scareports;

import java.math.BigDecimal;

import lombok.Getter;
import lombok.Setter;

/**
 * Auto-generated bean for Expense DTL 12a report.
 * Generated on 2025-08-01.
 */
@Getter
@Setter
public class ExpenseDtl12aBean implements SupplementalRecord {
    private BigDecimal _1_contact_info;
    private BigDecimal amount;
    private BigDecimal amount_10;
    private BigDecimal amount_11;
    private BigDecimal amount_12;
    private BigDecimal amount_13;
    private BigDecimal amount_14;
    private BigDecimal amount_15;
    private BigDecimal amount_16;
    private BigDecimal amount_17;
    private BigDecimal amount_18;
    private BigDecimal amount_19;
    private BigDecimal amount_2;
    private BigDecimal amount_20;
    private BigDecimal amount_21;
    private BigDecimal amount_22;
    private BigDecimal amount_23;
    private BigDecimal amount_24;
    private BigDecimal amount_25;
    private BigDecimal amount_26;
    private BigDecimal amount_27;
    private BigDecimal amount_28;
    private BigDecimal amount_29;
    private BigDecimal amount_3;
    private BigDecimal amount_30;
    private BigDecimal amount_31;
    private BigDecimal amount_32;
    private BigDecimal amount_33;
    private BigDecimal amount_34;
    private BigDecimal amount_35;
    private BigDecimal amount_4;
    private BigDecimal amount_5;
    private BigDecimal amount_6;
    private BigDecimal amount_7;
    private BigDecimal amount_8;
    private BigDecimal amount_9;
    private BigDecimal contents_b59;
    private BigDecimal contents_e_3;
    private BigDecimal contents_e_4;
    private BigDecimal oa_ar_or_fr;
    private BigDecimal oa_ar_or_fr_10;
    private BigDecimal oa_ar_or_fr_11;
    private BigDecimal oa_ar_or_fr_12;
    private BigDecimal oa_ar_or_fr_13;
    private BigDecimal oa_ar_or_fr_14;
    private BigDecimal oa_ar_or_fr_15;
    private BigDecimal oa_ar_or_fr_16;
    private BigDecimal oa_ar_or_fr_17;
    private BigDecimal oa_ar_or_fr_18;
    private BigDecimal oa_ar_or_fr_19;
    private BigDecimal oa_ar_or_fr_2;
    private BigDecimal oa_ar_or_fr_20;
    private BigDecimal oa_ar_or_fr_21;
    private BigDecimal oa_ar_or_fr_22;
    private BigDecimal oa_ar_or_fr_23;
    private BigDecimal oa_ar_or_fr_24;
    private BigDecimal oa_ar_or_fr_3;
    private BigDecimal oa_ar_or_fr_4;
    private BigDecimal oa_ar_or_fr_5;
    private BigDecimal oa_ar_or_fr_6;
    private BigDecimal oa_ar_or_fr_7;
    private BigDecimal oa_ar_or_fr_8;
    private BigDecimal oa_ar_or_fr_9;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_10;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_11;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_2;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_3;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_4;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_5;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_6;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_7;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_8;
    private BigDecimal organization_or_periodical_not_a_kingdom_newsletter_and_date_ad_was_published_9;
    private BigDecimal organization_or_person;
    private BigDecimal organization_or_person_10;
    private BigDecimal organization_or_person_11;
    private BigDecimal organization_or_person_12;
    private BigDecimal organization_or_person_13;
    private BigDecimal organization_or_person_14;
    private BigDecimal organization_or_person_15;
    private BigDecimal organization_or_person_16;
    private BigDecimal organization_or_person_17;
    private BigDecimal organization_or_person_18;
    private BigDecimal organization_or_person_19;
    private BigDecimal organization_or_person_2;
    private BigDecimal organization_or_person_20;
    private BigDecimal organization_or_person_21;
    private BigDecimal organization_or_person_22;
    private BigDecimal organization_or_person_23;
    private BigDecimal organization_or_person_24;
    private BigDecimal organization_or_person_3;
    private BigDecimal organization_or_person_4;
    private BigDecimal organization_or_person_5;
    private BigDecimal organization_or_person_6;
    private BigDecimal organization_or_person_7;
    private BigDecimal organization_or_person_8;
    private BigDecimal organization_or_person_9;
    private BigDecimal reason;
    private BigDecimal reason_10;
    private BigDecimal reason_11;
    private BigDecimal reason_12;
    private BigDecimal reason_2;
    private BigDecimal reason_3;
    private BigDecimal reason_4;
    private BigDecimal reason_5;
    private BigDecimal reason_6;
    private BigDecimal reason_7;
    private BigDecimal reason_8;
    private BigDecimal reason_9;
    private BigDecimal service_provided;
    private BigDecimal service_provided_10;
    private BigDecimal service_provided_11;
    private BigDecimal service_provided_12;
    private BigDecimal service_provided_2;
    private BigDecimal service_provided_3;
    private BigDecimal service_provided_4;
    private BigDecimal service_provided_5;
    private BigDecimal service_provided_6;
    private BigDecimal service_provided_7;
    private BigDecimal service_provided_8;
    private BigDecimal service_provided_9;
    private BigDecimal show_total_on_pg_4_line_12;
    private BigDecimal show_total_on_pg_4_line_13;
    private BigDecimal show_total_on_pg_4_line_17;
}