# Generated metadata for Jasper report bundle
displayName=Expense Detail 12b
generatorClass=nonprofitbookkeeping.reports.jasper.ExpenseDtl12bJasperGenerator
reportType=SCA_EXPENSE_DTL_12B_JASPER
template=EXPENSE_DTL_12b.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.ExpenseDtl12bBean
description=Expense detail schedule 12b. Data bean: ExpenseDtl12bBean.
beanName=expenseDtl12b
