# Generated metadata for Jasper report bundle
displayName=Secondary Accounts 2b
generatorClass=nonprofitbookkeeping.reports.jasper.SecondaryAccountJasperGenerator
reportType=SCA_SECONDARY_ACCOUNT_JASPER
template=SECONDARY_ACCOUNTS_2b.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.SecondaryAccounts2bBean
beanName=SecondaryAccounts2bBean
description=Secondary accounts schedule 2b. Data bean: SecondaryAccounts2bBean.
