-- SCLX/import run diagnostics.
--
-- V001 captured the current runtime core. This follow-up adds explicit
-- migration-owned import-run metadata so future repository-owned staging tables
-- can reference a stable run id instead of relying only on generic self-DDL.

CREATE TABLE IF NOT EXISTS sclx_import_run(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_name VARCHAR(255),
  source_fingerprint VARCHAR(128),
  imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  status VARCHAR(32) DEFAULT 'IMPORTED' NOT NULL,
  notes VARCHAR(1000),
  CONSTRAINT ck_sclx_import_run_status CHECK (status IN ('IMPORTED','PROMOTED','FAILED','CLEARED'))
);

CREATE INDEX IF NOT EXISTS ix_sclx_import_run_status_time
ON sclx_import_run(status, imported_at);

CREATE TABLE IF NOT EXISTS sclx_import_error(
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  import_run_id BIGINT,
  record_group VARCHAR(128),
  record_key VARCHAR(255),
  severity VARCHAR(16) DEFAULT 'ERROR' NOT NULL,
  message VARCHAR(2000) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT ck_sclx_import_error_severity CHECK (severity IN ('INFO','WARNING','ERROR')),
  CONSTRAINT fk_sclx_import_error_run FOREIGN KEY (import_run_id)
    REFERENCES sclx_import_run(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_sclx_import_error_run_group
ON sclx_import_error(import_run_id, record_group, severity);
