CREATE TABLE IF NOT EXISTS journal_transaction (
    id UUID PRIMARY KEY,
    group_code VARCHAR(64) NOT NULL,
    posted_on DATE NOT NULL,
    memo VARCHAR(512),
    bank_timing VARCHAR(32) NOT NULL,
    budget_timing VARCHAR(32) NOT NULL,
    reversed_transaction_id UUID NULL
);

CREATE TABLE IF NOT EXISTS journal_posting_line (
    transaction_id UUID NOT NULL,
    line_order INT NOT NULL,
    account_code VARCHAR(64) NOT NULL,
    fund_code VARCHAR(64) NOT NULL,
    entry_side VARCHAR(16) NOT NULL,
    amount DECIMAL(19, 2) NOT NULL,
    PRIMARY KEY (transaction_id, line_order),
    CONSTRAINT fk_journal_posting_line_txn
        FOREIGN KEY (transaction_id) REFERENCES journal_transaction(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS open_item_snapshot (
    id UUID PRIMARY KEY,
    group_code VARCHAR(64) NOT NULL,
    item_kind VARCHAR(64) NOT NULL,
    item_ref VARCHAR(255) NOT NULL,
    state VARCHAR(64) NOT NULL,
    original_amount DECIMAL(19, 2) NOT NULL,
    open_amount DECIMAL(19, 2) NOT NULL,
    last_transaction_id UUID NULL,
    last_updated_on DATE NOT NULL,
    version BIGINT NOT NULL,
    CONSTRAINT uq_open_item_snapshot_natural UNIQUE (group_code, item_kind, item_ref)
);

CREATE TABLE IF NOT EXISTS open_item_transition (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id UUID NOT NULL,
    transition_on DATE NOT NULL,
    from_state VARCHAR(64) NOT NULL,
    to_state VARCHAR(64) NOT NULL,
    trigger_transaction_id UUID NULL,
    notes VARCHAR(1024),
    CONSTRAINT fk_open_item_transition_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES open_item_snapshot(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS approval_audit_record (
    id UUID PRIMARY KEY,
    group_code VARCHAR(64) NOT NULL,
    workflow_type VARCHAR(128) NOT NULL,
    workflow_run_id UUID NULL,
    decision VARCHAR(32) NOT NULL,
    actor VARCHAR(128) NOT NULL,
    rationale VARCHAR(1024),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS reconciliation_run (
    id UUID PRIMARY KEY,
    group_code VARCHAR(64) NOT NULL,
    statement_ending_on DATE NOT NULL,
    bank_format VARCHAR(16) NOT NULL,
    imported_transaction_count INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    notes VARCHAR(1024),
    CONSTRAINT chk_reconciliation_run_bank_format CHECK (bank_format IN ('OFX', 'QFX')),
    CONSTRAINT chk_reconciliation_run_status CHECK (status IN ('STARTED', 'COMPLETED', 'FAILED'))
);

CREATE TABLE IF NOT EXISTS period_close_run (
    id UUID PRIMARY KEY,
    group_code VARCHAR(64) NOT NULL,
    close_date DATE NOT NULL,
    status VARCHAR(32) NOT NULL,
    produced_transaction_id UUID NULL,
    notes VARCHAR(1024),
    CONSTRAINT chk_period_close_run_status CHECK (status IN ('STARTED', 'COMPLETED', 'FAILED'))
);
