# Generated metadata for Jasper report bundle
displayName=Transfer In 9
generatorClass=nonprofitbookkeeping.reports.jasper.TransferIn9JasperGenerator
reportType=SCA_TRANSFER_IN_9_JASPER
template=TRANSFER_IN_9.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.TransferIn9Bean
beanName=TransferIn9Bean
description=Transfer in schedule 9. Data bean: TransferIn9Bean.
beanName=transferIn9
