# Generated metadata for Jasper report bundle
displayName=Income Detail 11b
generatorClass=nonprofitbookkeeping.reports.jasper.IncomeDtl11bJasperGenerator
reportType=SCA_INCOME_DTL_11B_JASPER
template=INCOME_DTL_11b.jrxml
beanClass=nonprofitbookkeeping.reports.datasource.scareports.IncomeDtl11bBean
beanName=IncomeDtl11bBean
description=Income detail schedule 11b. Data bean: IncomeDtl11bBean.
