
package nonprofitbookkeeping.reports.datasource;

import java.math.BigDecimal;

/**
 * Example generated bean for an "Account Summary" report.
 *
 * NOTE: In your actual project this will be generated by
 * the Excel→JRXML/bean generator, but the field naming here
 * matches the runtime mapping conventions.
 */
public class AccountSummaryRowBean
{
	
	private String accountname;
	private BigDecimal openingbalance;
	private BigDecimal closingbalance;
	
	public AccountSummaryRowBean()
	{
	
	}
	
	public String getAccountname()
	{
		return accountname;
		
	}
	
	public void setAccountname(String accountname)
	{
		this.accountname = accountname;
		
	}
	
	public BigDecimal getOpeningbalance()
	{
		return openingbalance;
		
	}
	
	public void setOpeningbalance(BigDecimal openingbalance)
	{
		this.openingbalance = openingbalance;
		
	}
	
	public BigDecimal getClosingbalance()
	{
		return closingbalance;
		
	}
	
	public void setClosingbalance(BigDecimal closingbalance)
	{
		this.closingbalance = closingbalance;
		
	}
	
}
